### ISSUE TITLE
0.2.2 fails npm install

### ISSUE THREAD

**Issue by jfhbrook** [heapwolf/codesurgeon#8] opened 2012-02-01 23:10 UTC
``` bash

npm info postuninstall codesurgeon@0.2.2

npm ERR! Error: ENOENT, no such file or directory '/home/josh/dev/broadway/node_modules/codesurgeon/node_modules/flatiron/node_modules/___broadway.npm/package/lib/broadway/bootstrapper.js'
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Linux 3.0.0-16-generic
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/josh/dev/broadway
npm ERR! node -v v0.6.6
npm ERR! npm -v 1.1.0-3
npm ERR! path /home/josh/dev/broadway/node_modules/codesurgeon/node_modules/flatiron/node_modules/___broadway.npm/package/lib/broadway/bootstrapper.js
npm ERR! fstream_path /home/josh/dev/broadway/node_modules/codesurgeon/node_modules/flatiron/node_modules/___broadway.npm/package/lib/broadway/bootstrapper.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chmod
npm ERR! code ENOENT
npm ERR! message ENOENT, no such file or directory '/home/josh/dev/broadway/node_modules/codesurgeon/node_modules/flatiron/node_modules/___broadway.npm/package/lib/broadway/bootstrapper.js'
npm ERR! errno {}
npm ERR! fstream_stack Object.oncomplete (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:285:17)

npm ERR! Error: ENOENT, no such file or directory '/home/josh/dev/broadway/node_modules/codesurgeon/node_modules/flatiron/node_modules/___prompt.npm/package/lib/prompt.js'
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Linux 3.0.0-16-generic
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/josh/dev/broadway
npm ERR! node -v v0.6.6
npm ERR! npm -v 1.1.0-3
npm ERR! path /home/josh/dev/broadway/node_modules/codesurgeon/node_modules/flatiron/node_modules/___prompt.npm/package/lib/prompt.js
npm ERR! fstream_path /home/josh/dev/broadway/node_modules/codesurgeon/node_modules/flatiron/node_modules/___prompt.npm/package/lib/prompt.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! message ENOENT, no such file or directory '/home/josh/dev/broadway/node_modules/codesurgeon/node_modules/flatiron/node_modules/___prompt.npm/package/lib/prompt.js'
npm ERR! errno {}
npm ERR! fstream_stack Object.oncomplete (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:204:26)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/josh/dev/broadway/npm-debug.log
npm not ok
```

**Comment by heapwolf** [comment] 2012-02-02 00:21
Not able to reproduce on any other machine or environment. I wonder if you have some bad flatiron modules (i'd imagine its possible since you hack on flatiron so much) can you try in another environment?

**Comment by jfhbrook** [comment] 2012-02-02 00:22
For some context, this came from doing a fresh install of Broadway. Maybe that particular project is doing something weird?

I'll see if I can get Avian to try this for me.

**Comment by heapwolf** [comment] 2012-02-02 01:01
@jesusabdullah im on node `v0.6.9`, but npm `1.1.0-3`, same as you. I'll run node `6.6` to see if that is the issue.

**Comment by heapwolf** [comment] 2012-02-02 01:03
@jesusabdullah instals ok on my Ubuntu 10.10 box with node v0.5.2

**Comment by jfhbrook** [comment] 2012-02-02 01:03
Sure.

fwiw, AvianFlu wasn't able to reproduce it.

**Comment by mmalecki** [comment] 2012-02-02 01:05
Works for me on `node v0.7.3-pre` and `npm 1.1.0`

**Comment by heapwolf** [comment] 2012-02-02 01:12
@jesusabdullah I'll close it for now and if you want just hit me up on IM or by email to see if i can help you! =)

**Closed as completed by heapwolf** 2012-02-02 01:12 UTC
